baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "mainroad"
uglyURLs = true

[permalinks]
[permalinks.term]
  tags = '/article-:filename-1.html'
[Params.logo]
  title = "Linux.cn Archive"

